// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.security.cryptoutility.message;

public final class MessageProtoc {
  private MessageProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.security.cryptoutility.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 protocolversion = 1;</code>
     * @return Whether the protocolversion field is set.
     */
    boolean hasProtocolversion();
    /**
     * <code>optional int32 protocolversion = 1;</code>
     * @return The protocolversion.
     */
    int getProtocolversion();

    /**
     * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
     * @return Whether the keysystem field is set.
     */
    boolean hasKeysystem();
    /**
     * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
     * @return The keysystem.
     */
    com.security.cryptoutility.message.MessageProtoc.Message.KeySystem getKeysystem();

    /**
     * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
     * @return Whether the encryptionalog field is set.
     */
    boolean hasEncryptionalog();
    /**
     * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
     * @return The encryptionalog.
     */
    com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo getEncryptionalog();

    /**
     * <code>optional int32 masterkeyversion = 4;</code>
     * @return Whether the masterkeyversion field is set.
     */
    boolean hasMasterkeyversion();
    /**
     * <code>optional int32 masterkeyversion = 4;</code>
     * @return The masterkeyversion.
     */
    int getMasterkeyversion();

    /**
     * <code>optional string masterkeyid = 5;</code>
     * @return Whether the masterkeyid field is set.
     */
    boolean hasMasterkeyid();
    /**
     * <code>optional string masterkeyid = 5;</code>
     * @return The masterkeyid.
     */
    java.lang.String getMasterkeyid();
    /**
     * <code>optional string masterkeyid = 5;</code>
     * @return The bytes for masterkeyid.
     */
    com.google.protobuf.ByteString
        getMasterkeyidBytes();

    /**
     * <code>optional string datakey = 6;</code>
     * @return Whether the datakey field is set.
     */
    boolean hasDatakey();
    /**
     * <code>optional string datakey = 6;</code>
     * @return The datakey.
     */
    java.lang.String getDatakey();
    /**
     * <code>optional string datakey = 6;</code>
     * @return The bytes for datakey.
     */
    com.google.protobuf.ByteString
        getDatakeyBytes();

    /**
     * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
     * @return Whether the signaturealgo field is set.
     */
    boolean hasSignaturealgo();
    /**
     * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
     * @return The signaturealgo.
     */
    com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo getSignaturealgo();

    /**
     * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
     * @return Whether the cipherdata field is set.
     */
    boolean hasCipherdata();
    /**
     * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
     * @return The cipherdata.
     */
    com.security.cryptoutility.message.MessageProtoc.Message.CipherData getCipherdata();
    /**
     * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
     */
    com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder getCipherdataOrBuilder();

    /**
     * <code>optional string signature = 9;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>optional string signature = 9;</code>
     * @return The signature.
     */
    java.lang.String getSignature();
    /**
     * <code>optional string signature = 9;</code>
     * @return The bytes for signature.
     */
    com.google.protobuf.ByteString
        getSignatureBytes();
  }
  /**
   * Protobuf type {@code com.security.cryptoutility.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.security.cryptoutility.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      keysystem_ = 0;
      encryptionalog_ = 0;
      masterkeyid_ = "";
      datakey_ = "";
      signaturealgo_ = 0;
      signature_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              protocolversion_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.security.cryptoutility.message.MessageProtoc.Message.KeySystem value = com.security.cryptoutility.message.MessageProtoc.Message.KeySystem.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                keysystem_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo value = com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                encryptionalog_ = rawValue;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              masterkeyversion_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              masterkeyid_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              datakey_ = bs;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo value = com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                signaturealgo_ = rawValue;
              }
              break;
            }
            case 66: {
              com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) != 0)) {
                subBuilder = cipherdata_.toBuilder();
              }
              cipherdata_ = input.readMessage(com.security.cryptoutility.message.MessageProtoc.Message.CipherData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cipherdata_);
                cipherdata_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              signature_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.security.cryptoutility.message.MessageProtoc.Message.class, com.security.cryptoutility.message.MessageProtoc.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code com.security.cryptoutility.Message.KeySystem}
     */
    public enum KeySystem
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>IDPS = 0;</code>
       */
      IDPS(0),
      /**
       * <code>KMS = 1;</code>
       */
      KMS(1),
      /**
       * <code>SAFENET = 2;</code>
       */
      SAFENET(2),
      ;

      /**
       * <code>IDPS = 0;</code>
       */
      public static final int IDPS_VALUE = 0;
      /**
       * <code>KMS = 1;</code>
       */
      public static final int KMS_VALUE = 1;
      /**
       * <code>SAFENET = 2;</code>
       */
      public static final int SAFENET_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static KeySystem valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static KeySystem forNumber(int value) {
        switch (value) {
          case 0: return IDPS;
          case 1: return KMS;
          case 2: return SAFENET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<KeySystem>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          KeySystem> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<KeySystem>() {
              public KeySystem findValueByNumber(int number) {
                return KeySystem.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.security.cryptoutility.message.MessageProtoc.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final KeySystem[] VALUES = values();

      public static KeySystem valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private KeySystem(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.security.cryptoutility.Message.KeySystem)
    }

    /**
     * Protobuf enum {@code com.security.cryptoutility.Message.EncryptionAlgo}
     */
    public enum EncryptionAlgo
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AES128 = 0;</code>
       */
      AES128(0),
      /**
       * <code>AES256 = 1;</code>
       */
      AES256(1),
      ;

      /**
       * <code>AES128 = 0;</code>
       */
      public static final int AES128_VALUE = 0;
      /**
       * <code>AES256 = 1;</code>
       */
      public static final int AES256_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EncryptionAlgo valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EncryptionAlgo forNumber(int value) {
        switch (value) {
          case 0: return AES128;
          case 1: return AES256;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EncryptionAlgo>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EncryptionAlgo> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EncryptionAlgo>() {
              public EncryptionAlgo findValueByNumber(int number) {
                return EncryptionAlgo.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.security.cryptoutility.message.MessageProtoc.Message.getDescriptor().getEnumTypes().get(1);
      }

      private static final EncryptionAlgo[] VALUES = values();

      public static EncryptionAlgo valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EncryptionAlgo(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.security.cryptoutility.Message.EncryptionAlgo)
    }

    /**
     * Protobuf enum {@code com.security.cryptoutility.Message.SignatureAlgo}
     */
    public enum SignatureAlgo
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HMACSHA256 = 0;</code>
       */
      HMACSHA256(0),
      ;

      /**
       * <code>HMACSHA256 = 0;</code>
       */
      public static final int HMACSHA256_VALUE = 0;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SignatureAlgo valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static SignatureAlgo forNumber(int value) {
        switch (value) {
          case 0: return HMACSHA256;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SignatureAlgo>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SignatureAlgo> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SignatureAlgo>() {
              public SignatureAlgo findValueByNumber(int number) {
                return SignatureAlgo.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.security.cryptoutility.message.MessageProtoc.Message.getDescriptor().getEnumTypes().get(2);
      }

      private static final SignatureAlgo[] VALUES = values();

      public static SignatureAlgo valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SignatureAlgo(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.security.cryptoutility.Message.SignatureAlgo)
    }

    public interface CipherDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.security.cryptoutility.Message.CipherData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bytes iv = 1;</code>
       * @return Whether the iv field is set.
       */
      boolean hasIv();
      /**
       * <code>optional bytes iv = 1;</code>
       * @return The iv.
       */
      com.google.protobuf.ByteString getIv();

      /**
       * <code>optional bytes encrypted = 2;</code>
       * @return Whether the encrypted field is set.
       */
      boolean hasEncrypted();
      /**
       * <code>optional bytes encrypted = 2;</code>
       * @return The encrypted.
       */
      com.google.protobuf.ByteString getEncrypted();
    }
    /**
     * Protobuf type {@code com.security.cryptoutility.Message.CipherData}
     */
    public static final class CipherData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.security.cryptoutility.Message.CipherData)
        CipherDataOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CipherData.newBuilder() to construct.
      private CipherData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CipherData() {
        iv_ = com.google.protobuf.ByteString.EMPTY;
        encrypted_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new CipherData();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private CipherData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bitField0_ |= 0x00000001;
                iv_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                encrypted_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_CipherData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_CipherData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.security.cryptoutility.message.MessageProtoc.Message.CipherData.class, com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder.class);
      }

      private int bitField0_;
      public static final int IV_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString iv_;
      /**
       * <code>optional bytes iv = 1;</code>
       * @return Whether the iv field is set.
       */
      @java.lang.Override
      public boolean hasIv() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes iv = 1;</code>
       * @return The iv.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }

      public static final int ENCRYPTED_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString encrypted_;
      /**
       * <code>optional bytes encrypted = 2;</code>
       * @return Whether the encrypted field is set.
       */
      @java.lang.Override
      public boolean hasEncrypted() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes encrypted = 2;</code>
       * @return The encrypted.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncrypted() {
        return encrypted_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeBytes(1, iv_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeBytes(2, encrypted_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, iv_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, encrypted_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.security.cryptoutility.message.MessageProtoc.Message.CipherData)) {
          return super.equals(obj);
        }
        com.security.cryptoutility.message.MessageProtoc.Message.CipherData other = (com.security.cryptoutility.message.MessageProtoc.Message.CipherData) obj;

        if (hasIv() != other.hasIv()) return false;
        if (hasIv()) {
          if (!getIv()
              .equals(other.getIv())) return false;
        }
        if (hasEncrypted() != other.hasEncrypted()) return false;
        if (hasEncrypted()) {
          if (!getEncrypted()
              .equals(other.getEncrypted())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasIv()) {
          hash = (37 * hash) + IV_FIELD_NUMBER;
          hash = (53 * hash) + getIv().hashCode();
        }
        if (hasEncrypted()) {
          hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
          hash = (53 * hash) + getEncrypted().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.security.cryptoutility.message.MessageProtoc.Message.CipherData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.security.cryptoutility.Message.CipherData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.security.cryptoutility.Message.CipherData)
          com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_CipherData_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_CipherData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.security.cryptoutility.message.MessageProtoc.Message.CipherData.class, com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder.class);
        }

        // Construct using com.security.cryptoutility.message.MessageProtoc.Message.CipherData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          iv_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          encrypted_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_CipherData_descriptor;
        }

        @java.lang.Override
        public com.security.cryptoutility.message.MessageProtoc.Message.CipherData getDefaultInstanceForType() {
          return com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance();
        }

        @java.lang.Override
        public com.security.cryptoutility.message.MessageProtoc.Message.CipherData build() {
          com.security.cryptoutility.message.MessageProtoc.Message.CipherData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.security.cryptoutility.message.MessageProtoc.Message.CipherData buildPartial() {
          com.security.cryptoutility.message.MessageProtoc.Message.CipherData result = new com.security.cryptoutility.message.MessageProtoc.Message.CipherData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.iv_ = iv_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.encrypted_ = encrypted_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.security.cryptoutility.message.MessageProtoc.Message.CipherData) {
            return mergeFrom((com.security.cryptoutility.message.MessageProtoc.Message.CipherData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.security.cryptoutility.message.MessageProtoc.Message.CipherData other) {
          if (other == com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance()) return this;
          if (other.hasIv()) {
            setIv(other.getIv());
          }
          if (other.hasEncrypted()) {
            setEncrypted(other.getEncrypted());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.security.cryptoutility.message.MessageProtoc.Message.CipherData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.security.cryptoutility.message.MessageProtoc.Message.CipherData) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes iv = 1;</code>
         * @return Whether the iv field is set.
         */
        @java.lang.Override
        public boolean hasIv() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional bytes iv = 1;</code>
         * @return The iv.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getIv() {
          return iv_;
        }
        /**
         * <code>optional bytes iv = 1;</code>
         * @param value The iv to set.
         * @return This builder for chaining.
         */
        public Builder setIv(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          iv_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes iv = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearIv() {
          bitField0_ = (bitField0_ & ~0x00000001);
          iv_ = getDefaultInstance().getIv();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString encrypted_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes encrypted = 2;</code>
         * @return Whether the encrypted field is set.
         */
        @java.lang.Override
        public boolean hasEncrypted() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional bytes encrypted = 2;</code>
         * @return The encrypted.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getEncrypted() {
          return encrypted_;
        }
        /**
         * <code>optional bytes encrypted = 2;</code>
         * @param value The encrypted to set.
         * @return This builder for chaining.
         */
        public Builder setEncrypted(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          encrypted_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes encrypted = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearEncrypted() {
          bitField0_ = (bitField0_ & ~0x00000002);
          encrypted_ = getDefaultInstance().getEncrypted();
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.security.cryptoutility.Message.CipherData)
      }

      // @@protoc_insertion_point(class_scope:com.security.cryptoutility.Message.CipherData)
      private static final com.security.cryptoutility.message.MessageProtoc.Message.CipherData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.security.cryptoutility.message.MessageProtoc.Message.CipherData();
      }

      public static com.security.cryptoutility.message.MessageProtoc.Message.CipherData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<CipherData>
          PARSER = new com.google.protobuf.AbstractParser<CipherData>() {
        @java.lang.Override
        public CipherData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CipherData(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<CipherData> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CipherData> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message.CipherData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PROTOCOLVERSION_FIELD_NUMBER = 1;
    private int protocolversion_;
    /**
     * <code>optional int32 protocolversion = 1;</code>
     * @return Whether the protocolversion field is set.
     */
    @java.lang.Override
    public boolean hasProtocolversion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 protocolversion = 1;</code>
     * @return The protocolversion.
     */
    @java.lang.Override
    public int getProtocolversion() {
      return protocolversion_;
    }

    public static final int KEYSYSTEM_FIELD_NUMBER = 2;
    private int keysystem_;
    /**
     * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
     * @return Whether the keysystem field is set.
     */
    @java.lang.Override public boolean hasKeysystem() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
     * @return The keysystem.
     */
    @java.lang.Override public com.security.cryptoutility.message.MessageProtoc.Message.KeySystem getKeysystem() {
      @SuppressWarnings("deprecation")
      com.security.cryptoutility.message.MessageProtoc.Message.KeySystem result = com.security.cryptoutility.message.MessageProtoc.Message.KeySystem.valueOf(keysystem_);
      return result == null ? com.security.cryptoutility.message.MessageProtoc.Message.KeySystem.IDPS : result;
    }

    public static final int ENCRYPTIONALOG_FIELD_NUMBER = 3;
    private int encryptionalog_;
    /**
     * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
     * @return Whether the encryptionalog field is set.
     */
    @java.lang.Override public boolean hasEncryptionalog() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
     * @return The encryptionalog.
     */
    @java.lang.Override public com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo getEncryptionalog() {
      @SuppressWarnings("deprecation")
      com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo result = com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo.valueOf(encryptionalog_);
      return result == null ? com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo.AES128 : result;
    }

    public static final int MASTERKEYVERSION_FIELD_NUMBER = 4;
    private int masterkeyversion_;
    /**
     * <code>optional int32 masterkeyversion = 4;</code>
     * @return Whether the masterkeyversion field is set.
     */
    @java.lang.Override
    public boolean hasMasterkeyversion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 masterkeyversion = 4;</code>
     * @return The masterkeyversion.
     */
    @java.lang.Override
    public int getMasterkeyversion() {
      return masterkeyversion_;
    }

    public static final int MASTERKEYID_FIELD_NUMBER = 5;
    private volatile java.lang.Object masterkeyid_;
    /**
     * <code>optional string masterkeyid = 5;</code>
     * @return Whether the masterkeyid field is set.
     */
    @java.lang.Override
    public boolean hasMasterkeyid() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string masterkeyid = 5;</code>
     * @return The masterkeyid.
     */
    @java.lang.Override
    public java.lang.String getMasterkeyid() {
      java.lang.Object ref = masterkeyid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          masterkeyid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string masterkeyid = 5;</code>
     * @return The bytes for masterkeyid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMasterkeyidBytes() {
      java.lang.Object ref = masterkeyid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        masterkeyid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAKEY_FIELD_NUMBER = 6;
    private volatile java.lang.Object datakey_;
    /**
     * <code>optional string datakey = 6;</code>
     * @return Whether the datakey field is set.
     */
    @java.lang.Override
    public boolean hasDatakey() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string datakey = 6;</code>
     * @return The datakey.
     */
    @java.lang.Override
    public java.lang.String getDatakey() {
      java.lang.Object ref = datakey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          datakey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string datakey = 6;</code>
     * @return The bytes for datakey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDatakeyBytes() {
      java.lang.Object ref = datakey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datakey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATUREALGO_FIELD_NUMBER = 7;
    private int signaturealgo_;
    /**
     * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
     * @return Whether the signaturealgo field is set.
     */
    @java.lang.Override public boolean hasSignaturealgo() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
     * @return The signaturealgo.
     */
    @java.lang.Override public com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo getSignaturealgo() {
      @SuppressWarnings("deprecation")
      com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo result = com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo.valueOf(signaturealgo_);
      return result == null ? com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo.HMACSHA256 : result;
    }

    public static final int CIPHERDATA_FIELD_NUMBER = 8;
    private com.security.cryptoutility.message.MessageProtoc.Message.CipherData cipherdata_;
    /**
     * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
     * @return Whether the cipherdata field is set.
     */
    @java.lang.Override
    public boolean hasCipherdata() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
     * @return The cipherdata.
     */
    @java.lang.Override
    public com.security.cryptoutility.message.MessageProtoc.Message.CipherData getCipherdata() {
      return cipherdata_ == null ? com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance() : cipherdata_;
    }
    /**
     * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
     */
    @java.lang.Override
    public com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder getCipherdataOrBuilder() {
      return cipherdata_ == null ? com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance() : cipherdata_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 9;
    private volatile java.lang.Object signature_;
    /**
     * <code>optional string signature = 9;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string signature = 9;</code>
     * @return The signature.
     */
    @java.lang.Override
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string signature = 9;</code>
     * @return The bytes for signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, protocolversion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, keysystem_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, encryptionalog_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, masterkeyversion_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, masterkeyid_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, datakey_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(7, signaturealgo_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeMessage(8, getCipherdata());
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, protocolversion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, keysystem_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, encryptionalog_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, masterkeyversion_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, masterkeyid_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, datakey_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, signaturealgo_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getCipherdata());
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.security.cryptoutility.message.MessageProtoc.Message)) {
        return super.equals(obj);
      }
      com.security.cryptoutility.message.MessageProtoc.Message other = (com.security.cryptoutility.message.MessageProtoc.Message) obj;

      if (hasProtocolversion() != other.hasProtocolversion()) return false;
      if (hasProtocolversion()) {
        if (getProtocolversion()
            != other.getProtocolversion()) return false;
      }
      if (hasKeysystem() != other.hasKeysystem()) return false;
      if (hasKeysystem()) {
        if (keysystem_ != other.keysystem_) return false;
      }
      if (hasEncryptionalog() != other.hasEncryptionalog()) return false;
      if (hasEncryptionalog()) {
        if (encryptionalog_ != other.encryptionalog_) return false;
      }
      if (hasMasterkeyversion() != other.hasMasterkeyversion()) return false;
      if (hasMasterkeyversion()) {
        if (getMasterkeyversion()
            != other.getMasterkeyversion()) return false;
      }
      if (hasMasterkeyid() != other.hasMasterkeyid()) return false;
      if (hasMasterkeyid()) {
        if (!getMasterkeyid()
            .equals(other.getMasterkeyid())) return false;
      }
      if (hasDatakey() != other.hasDatakey()) return false;
      if (hasDatakey()) {
        if (!getDatakey()
            .equals(other.getDatakey())) return false;
      }
      if (hasSignaturealgo() != other.hasSignaturealgo()) return false;
      if (hasSignaturealgo()) {
        if (signaturealgo_ != other.signaturealgo_) return false;
      }
      if (hasCipherdata() != other.hasCipherdata()) return false;
      if (hasCipherdata()) {
        if (!getCipherdata()
            .equals(other.getCipherdata())) return false;
      }
      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtocolversion()) {
        hash = (37 * hash) + PROTOCOLVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolversion();
      }
      if (hasKeysystem()) {
        hash = (37 * hash) + KEYSYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + keysystem_;
      }
      if (hasEncryptionalog()) {
        hash = (37 * hash) + ENCRYPTIONALOG_FIELD_NUMBER;
        hash = (53 * hash) + encryptionalog_;
      }
      if (hasMasterkeyversion()) {
        hash = (37 * hash) + MASTERKEYVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getMasterkeyversion();
      }
      if (hasMasterkeyid()) {
        hash = (37 * hash) + MASTERKEYID_FIELD_NUMBER;
        hash = (53 * hash) + getMasterkeyid().hashCode();
      }
      if (hasDatakey()) {
        hash = (37 * hash) + DATAKEY_FIELD_NUMBER;
        hash = (53 * hash) + getDatakey().hashCode();
      }
      if (hasSignaturealgo()) {
        hash = (37 * hash) + SIGNATUREALGO_FIELD_NUMBER;
        hash = (53 * hash) + signaturealgo_;
      }
      if (hasCipherdata()) {
        hash = (37 * hash) + CIPHERDATA_FIELD_NUMBER;
        hash = (53 * hash) + getCipherdata().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.security.cryptoutility.message.MessageProtoc.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.security.cryptoutility.message.MessageProtoc.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.security.cryptoutility.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.security.cryptoutility.Message)
        com.security.cryptoutility.message.MessageProtoc.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.security.cryptoutility.message.MessageProtoc.Message.class, com.security.cryptoutility.message.MessageProtoc.Message.Builder.class);
      }

      // Construct using com.security.cryptoutility.message.MessageProtoc.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCipherdataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protocolversion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        keysystem_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptionalog_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        masterkeyversion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        masterkeyid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        datakey_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        signaturealgo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (cipherdataBuilder_ == null) {
          cipherdata_ = null;
        } else {
          cipherdataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.security.cryptoutility.message.MessageProtoc.internal_static_com_security_cryptoutility_Message_descriptor;
      }

      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message getDefaultInstanceForType() {
        return com.security.cryptoutility.message.MessageProtoc.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message build() {
        com.security.cryptoutility.message.MessageProtoc.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message buildPartial() {
        com.security.cryptoutility.message.MessageProtoc.Message result = new com.security.cryptoutility.message.MessageProtoc.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protocolversion_ = protocolversion_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.keysystem_ = keysystem_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.encryptionalog_ = encryptionalog_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.masterkeyversion_ = masterkeyversion_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.masterkeyid_ = masterkeyid_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.datakey_ = datakey_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.signaturealgo_ = signaturealgo_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          if (cipherdataBuilder_ == null) {
            result.cipherdata_ = cipherdata_;
          } else {
            result.cipherdata_ = cipherdataBuilder_.build();
          }
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.security.cryptoutility.message.MessageProtoc.Message) {
          return mergeFrom((com.security.cryptoutility.message.MessageProtoc.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.security.cryptoutility.message.MessageProtoc.Message other) {
        if (other == com.security.cryptoutility.message.MessageProtoc.Message.getDefaultInstance()) return this;
        if (other.hasProtocolversion()) {
          setProtocolversion(other.getProtocolversion());
        }
        if (other.hasKeysystem()) {
          setKeysystem(other.getKeysystem());
        }
        if (other.hasEncryptionalog()) {
          setEncryptionalog(other.getEncryptionalog());
        }
        if (other.hasMasterkeyversion()) {
          setMasterkeyversion(other.getMasterkeyversion());
        }
        if (other.hasMasterkeyid()) {
          bitField0_ |= 0x00000010;
          masterkeyid_ = other.masterkeyid_;
          onChanged();
        }
        if (other.hasDatakey()) {
          bitField0_ |= 0x00000020;
          datakey_ = other.datakey_;
          onChanged();
        }
        if (other.hasSignaturealgo()) {
          setSignaturealgo(other.getSignaturealgo());
        }
        if (other.hasCipherdata()) {
          mergeCipherdata(other.getCipherdata());
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000100;
          signature_ = other.signature_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.security.cryptoutility.message.MessageProtoc.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.security.cryptoutility.message.MessageProtoc.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protocolversion_ ;
      /**
       * <code>optional int32 protocolversion = 1;</code>
       * @return Whether the protocolversion field is set.
       */
      @java.lang.Override
      public boolean hasProtocolversion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 protocolversion = 1;</code>
       * @return The protocolversion.
       */
      @java.lang.Override
      public int getProtocolversion() {
        return protocolversion_;
      }
      /**
       * <code>optional int32 protocolversion = 1;</code>
       * @param value The protocolversion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolversion(int value) {
        bitField0_ |= 0x00000001;
        protocolversion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 protocolversion = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolversion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolversion_ = 0;
        onChanged();
        return this;
      }

      private int keysystem_ = 0;
      /**
       * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
       * @return Whether the keysystem field is set.
       */
      @java.lang.Override public boolean hasKeysystem() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
       * @return The keysystem.
       */
      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message.KeySystem getKeysystem() {
        @SuppressWarnings("deprecation")
        com.security.cryptoutility.message.MessageProtoc.Message.KeySystem result = com.security.cryptoutility.message.MessageProtoc.Message.KeySystem.valueOf(keysystem_);
        return result == null ? com.security.cryptoutility.message.MessageProtoc.Message.KeySystem.IDPS : result;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
       * @param value The keysystem to set.
       * @return This builder for chaining.
       */
      public Builder setKeysystem(com.security.cryptoutility.message.MessageProtoc.Message.KeySystem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        keysystem_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.KeySystem keysystem = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeysystem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        keysystem_ = 0;
        onChanged();
        return this;
      }

      private int encryptionalog_ = 0;
      /**
       * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
       * @return Whether the encryptionalog field is set.
       */
      @java.lang.Override public boolean hasEncryptionalog() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
       * @return The encryptionalog.
       */
      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo getEncryptionalog() {
        @SuppressWarnings("deprecation")
        com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo result = com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo.valueOf(encryptionalog_);
        return result == null ? com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo.AES128 : result;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
       * @param value The encryptionalog to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptionalog(com.security.cryptoutility.message.MessageProtoc.Message.EncryptionAlgo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        encryptionalog_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.EncryptionAlgo encryptionalog = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptionalog() {
        bitField0_ = (bitField0_ & ~0x00000004);
        encryptionalog_ = 0;
        onChanged();
        return this;
      }

      private int masterkeyversion_ ;
      /**
       * <code>optional int32 masterkeyversion = 4;</code>
       * @return Whether the masterkeyversion field is set.
       */
      @java.lang.Override
      public boolean hasMasterkeyversion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 masterkeyversion = 4;</code>
       * @return The masterkeyversion.
       */
      @java.lang.Override
      public int getMasterkeyversion() {
        return masterkeyversion_;
      }
      /**
       * <code>optional int32 masterkeyversion = 4;</code>
       * @param value The masterkeyversion to set.
       * @return This builder for chaining.
       */
      public Builder setMasterkeyversion(int value) {
        bitField0_ |= 0x00000008;
        masterkeyversion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 masterkeyversion = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMasterkeyversion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        masterkeyversion_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object masterkeyid_ = "";
      /**
       * <code>optional string masterkeyid = 5;</code>
       * @return Whether the masterkeyid field is set.
       */
      public boolean hasMasterkeyid() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string masterkeyid = 5;</code>
       * @return The masterkeyid.
       */
      public java.lang.String getMasterkeyid() {
        java.lang.Object ref = masterkeyid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            masterkeyid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string masterkeyid = 5;</code>
       * @return The bytes for masterkeyid.
       */
      public com.google.protobuf.ByteString
          getMasterkeyidBytes() {
        java.lang.Object ref = masterkeyid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          masterkeyid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string masterkeyid = 5;</code>
       * @param value The masterkeyid to set.
       * @return This builder for chaining.
       */
      public Builder setMasterkeyid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        masterkeyid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string masterkeyid = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMasterkeyid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        masterkeyid_ = getDefaultInstance().getMasterkeyid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string masterkeyid = 5;</code>
       * @param value The bytes for masterkeyid to set.
       * @return This builder for chaining.
       */
      public Builder setMasterkeyidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        masterkeyid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object datakey_ = "";
      /**
       * <code>optional string datakey = 6;</code>
       * @return Whether the datakey field is set.
       */
      public boolean hasDatakey() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string datakey = 6;</code>
       * @return The datakey.
       */
      public java.lang.String getDatakey() {
        java.lang.Object ref = datakey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            datakey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string datakey = 6;</code>
       * @return The bytes for datakey.
       */
      public com.google.protobuf.ByteString
          getDatakeyBytes() {
        java.lang.Object ref = datakey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datakey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string datakey = 6;</code>
       * @param value The datakey to set.
       * @return This builder for chaining.
       */
      public Builder setDatakey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        datakey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string datakey = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatakey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        datakey_ = getDefaultInstance().getDatakey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string datakey = 6;</code>
       * @param value The bytes for datakey to set.
       * @return This builder for chaining.
       */
      public Builder setDatakeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        datakey_ = value;
        onChanged();
        return this;
      }

      private int signaturealgo_ = 0;
      /**
       * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
       * @return Whether the signaturealgo field is set.
       */
      @java.lang.Override public boolean hasSignaturealgo() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
       * @return The signaturealgo.
       */
      @java.lang.Override
      public com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo getSignaturealgo() {
        @SuppressWarnings("deprecation")
        com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo result = com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo.valueOf(signaturealgo_);
        return result == null ? com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo.HMACSHA256 : result;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
       * @param value The signaturealgo to set.
       * @return This builder for chaining.
       */
      public Builder setSignaturealgo(com.security.cryptoutility.message.MessageProtoc.Message.SignatureAlgo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        signaturealgo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.SignatureAlgo signaturealgo = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignaturealgo() {
        bitField0_ = (bitField0_ & ~0x00000040);
        signaturealgo_ = 0;
        onChanged();
        return this;
      }

      private com.security.cryptoutility.message.MessageProtoc.Message.CipherData cipherdata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.security.cryptoutility.message.MessageProtoc.Message.CipherData, com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder, com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder> cipherdataBuilder_;
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       * @return Whether the cipherdata field is set.
       */
      public boolean hasCipherdata() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       * @return The cipherdata.
       */
      public com.security.cryptoutility.message.MessageProtoc.Message.CipherData getCipherdata() {
        if (cipherdataBuilder_ == null) {
          return cipherdata_ == null ? com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance() : cipherdata_;
        } else {
          return cipherdataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      public Builder setCipherdata(com.security.cryptoutility.message.MessageProtoc.Message.CipherData value) {
        if (cipherdataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cipherdata_ = value;
          onChanged();
        } else {
          cipherdataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      public Builder setCipherdata(
          com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder builderForValue) {
        if (cipherdataBuilder_ == null) {
          cipherdata_ = builderForValue.build();
          onChanged();
        } else {
          cipherdataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      public Builder mergeCipherdata(com.security.cryptoutility.message.MessageProtoc.Message.CipherData value) {
        if (cipherdataBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
              cipherdata_ != null &&
              cipherdata_ != com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance()) {
            cipherdata_ =
              com.security.cryptoutility.message.MessageProtoc.Message.CipherData.newBuilder(cipherdata_).mergeFrom(value).buildPartial();
          } else {
            cipherdata_ = value;
          }
          onChanged();
        } else {
          cipherdataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      public Builder clearCipherdata() {
        if (cipherdataBuilder_ == null) {
          cipherdata_ = null;
          onChanged();
        } else {
          cipherdataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      public com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder getCipherdataBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getCipherdataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      public com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder getCipherdataOrBuilder() {
        if (cipherdataBuilder_ != null) {
          return cipherdataBuilder_.getMessageOrBuilder();
        } else {
          return cipherdata_ == null ?
              com.security.cryptoutility.message.MessageProtoc.Message.CipherData.getDefaultInstance() : cipherdata_;
        }
      }
      /**
       * <code>optional .com.security.cryptoutility.Message.CipherData cipherdata = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.security.cryptoutility.message.MessageProtoc.Message.CipherData, com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder, com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder> 
          getCipherdataFieldBuilder() {
        if (cipherdataBuilder_ == null) {
          cipherdataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.security.cryptoutility.message.MessageProtoc.Message.CipherData, com.security.cryptoutility.message.MessageProtoc.Message.CipherData.Builder, com.security.cryptoutility.message.MessageProtoc.Message.CipherDataOrBuilder>(
                  getCipherdata(),
                  getParentForChildren(),
                  isClean());
          cipherdata_ = null;
        }
        return cipherdataBuilder_;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>optional string signature = 9;</code>
       * @return Whether the signature field is set.
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string signature = 9;</code>
       * @return The signature.
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string signature = 9;</code>
       * @return The bytes for signature.
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string signature = 9;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000100);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 9;</code>
       * @param value The bytes for signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        signature_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.security.cryptoutility.Message)
    }

    // @@protoc_insertion_point(class_scope:com.security.cryptoutility.Message)
    private static final com.security.cryptoutility.message.MessageProtoc.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.security.cryptoutility.message.MessageProtoc.Message();
    }

    public static com.security.cryptoutility.message.MessageProtoc.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.security.cryptoutility.message.MessageProtoc.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_security_cryptoutility_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_security_cryptoutility_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_security_cryptoutility_Message_CipherData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_security_cryptoutility_Message_CipherData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\032com.security.cryptoutil" +
      "ity\"\266\004\n\007Message\022\027\n\017protocolversion\030\001 \001(\005" +
      "\022@\n\tkeysystem\030\002 \001(\0162-.com.security.crypt" +
      "outility.Message.KeySystem\022J\n\016encryption" +
      "alog\030\003 \001(\01622.com.security.cryptoutility." +
      "Message.EncryptionAlgo\022\030\n\020masterkeyversi" +
      "on\030\004 \001(\005\022\023\n\013masterkeyid\030\005 \001(\t\022\017\n\007datakey" +
      "\030\006 \001(\t\022H\n\rsignaturealgo\030\007 \001(\01621.com.secu" +
      "rity.cryptoutility.Message.SignatureAlgo" +
      "\022B\n\ncipherdata\030\010 \001(\0132..com.security.cryp" +
      "toutility.Message.CipherData\022\021\n\tsignatur" +
      "e\030\t \001(\t\032+\n\nCipherData\022\n\n\002iv\030\001 \001(\014\022\021\n\tenc" +
      "rypted\030\002 \001(\014\"+\n\tKeySystem\022\010\n\004IDPS\020\000\022\007\n\003K" +
      "MS\020\001\022\013\n\007SAFENET\020\002\"(\n\016EncryptionAlgo\022\n\n\006A" +
      "ES128\020\000\022\n\n\006AES256\020\001\"\037\n\rSignatureAlgo\022\016\n\n" +
      "HMACSHA256\020\000B3\n\"com.security.cryptoutili" +
      "ty.messageB\rMessageProtoc"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_security_cryptoutility_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_security_cryptoutility_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_security_cryptoutility_Message_descriptor,
        new java.lang.String[] { "Protocolversion", "Keysystem", "Encryptionalog", "Masterkeyversion", "Masterkeyid", "Datakey", "Signaturealgo", "Cipherdata", "Signature", });
    internal_static_com_security_cryptoutility_Message_CipherData_descriptor =
      internal_static_com_security_cryptoutility_Message_descriptor.getNestedTypes().get(0);
    internal_static_com_security_cryptoutility_Message_CipherData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_security_cryptoutility_Message_CipherData_descriptor,
        new java.lang.String[] { "Iv", "Encrypted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
